export const sources = [
 {title:'CANN 架构与开发入口',version:'商用版 8.2.RC1',url:'https://www.hiascend.com/document/detail/zh/canncommercial/82RC1/index/index.html'},
 {title:'Ascend C 编程接口概述',version:'社区版 8.2.RC1.alpha003',url:'https://www.hiascend.com/document/detail/zh/CANNCommunityEdition/82RC1alpha003/opdevg/Ascendcopdevg/atlas_ascendc_10_0018.html'},
 {title:'算子实现与 Tiling',version:'社区版 8.2.RC1.alpha003',url:'https://www.hiascend.com/document/detail/zh/CANNCommunityEdition/82RC1alpha003/opdevg/Ascendcopdevg/atlas_ascendc_10_0031.html'},
 {title:'Add 核函数直调官方样例',version:'samples · v1.0-8.1.RC1.alpha001',url:'https://gitee.com/ascend/samples/blob/v1.0-8.1.RC1.alpha001/operator/ascendc/0_introduction/3_add_kernellaunch/AddKernelInvocationNeo/add_custom.cpp'},
 {title:'TPipe::InitBuffer 接口',version:'商用版 8.2.RC1',url:'https://www.hiascend.com/document/detail/zh/canncommercial/82RC1/API/ascendcopapi/atlasascendc_api_07_0110.html'},
 {title:'Ascend C API 列表',version:'社区版 8.2.RC1.alpha003',url:'https://www.hiascend.com/document/detail/zh/CANNCommunityEdition/82RC1alpha003/API/ascendcopapi'}
];
export const modules = [
 {title:'从 AI 到昇腾计算',chapter:'第一章 · 核心概念',time:75,slot:'09:00—10:15',tag:'建立全局视角',original:'章节介绍；人工智能与算子基础；CANN 架构与昇腾 NPU 原理。',goal:'能说明模型、算子、软件栈与硬件之间的关系。',points:[['模型由算子连接而成','模型描述任务所需的计算流程；算子完成其中一个具体计算，例如加法、矩阵乘法。张量是数据的组织方式，阅读算子时先确认形状、数据类型和输入输出。'],['CANN 连接框架与硬件','CANN 向上对接 AI 框架，向下服务昇腾 AI 处理器。Atlas 是需要认识的昇腾产品系列；学习环境应记录实际设备型号，不能只凭产品系列推断支持的 API。'],['先认识并行，再讨论性能','把较大的输入分配给多个 AI Core，是理解并行的入口。核内还需安排数据搬运与计算，具体计算单元及存储能力以所用芯片文档为准。']],exercise:'画出“AI 应用 → 框架 → CANN → 昇腾硬件”四层图，并把模型、算子和张量放到合适的位置。补充一个 AI 应用实例及其可能用到的算子。',refs:[0]},
 {title:'认识 Ascend C 与 Kernel',chapter:'第一章 · 核心概念',time:60,slot:'10:30—11:30',tag:'理解开发分工',original:'Ascend C 算子开发基本概念；第一章课后练习。',goal:'区分 Host 与 Device，理解核函数直调的边界。',points:[['Host 负责组织一次调用','主机侧准备数据与资源，设置调用参数，发起核函数调用，并在合适的同步点读取结果、释放资源。不能把发起调用等同于计算已经结束。'],['Kernel 负责设备侧计算','核函数实现对分配到本核的数据进行处理。阅读核函数时依次确认入口参数、初始化、计算流程和访问范围。'],['“直调”是一条开发路径','Kernel 直调聚焦主机调用核函数的完整链路。它与把算子接入框架的工程化开发不是同一个交付范围。先跑通正确性，再逐步理解工程集成。']],exercise:'用两列写出 Host 和 Device 的职责；不看笔记说明一次调用从分配资源到释放资源的过程。',refs:[1,2,3]},
 {title:'跑通第一个 Hello world',chapter:'第二章 · 开发基础',time:45,slot:'13:45—14:30',tag:'完成首次调用',original:'章节介绍；Ascend C 的 Hello world。',goal:'建立环境、构建、执行和验证的基本闭环。',points:[['先记录环境，再执行样例','记录芯片型号、驱动/固件、CANN Toolkit 版本及样例分支。按对应版本的官方安装与样例说明准备环境，避免混用不同版本的构建命令。'],['把“编译”和“验证”分开','构建成功只能说明生成了目标文件。执行后还要查看返回信息与输出；保存日志，才能复现问题。'],['从最小样例定位故障','依次排查环境是否就绪、构建是否成功、设备调用是否完成、输出是否符合预期。此网页提供学习指导，不连接昇腾设备，也不执行或模拟编译。']],exercise:'在真实昇腾环境运行匹配版本的入门样例，把环境版本、命令、日志和输出写入笔记；没有环境时先完成代码阅读，不勾选“运行通过”。',refs:[0,3]},
 {title:'读懂 Add 的三段流水',chapter:'第二章 · 开发基础',time:45,slot:'14:45—15:30',tag:'搬入 · 计算 · 写回',original:'Ascend C 编程范式和 API；基于 Add 算子的核函数介绍。',goal:'理解 TPipe、TQue、TBuf 和 Add 的数据流。',points:[['CopyIn：先把数据搬进来','DataCopy 用于搬运数据；GlobalTensor 与 LocalTensor 分别帮助访问全局与局部数据。先核对元素个数、数据类型和偏移，再核对接口约束。'],['Compute：在局部数据上计算','Add 样例在局部张量上逐元素相加。TQue 的入队/出队组织阶段间的数据传递与同步；AllocTensor/FreeTensor 管理张量的使用周期。'],['CopyOut：结果写回才算闭环','输出队列中的结果搬回全局内存后释放对应局部张量。TPipe 为 TQue/TBuf 分配所需存储，TBuf 适合临时计算数据，不提供队列的入队/出队语义。']],exercise:'对照官方 Add 样例，分别找到搬入、计算、写回的位置，解释每个队列什么时候分配、入队、出队和释放。',refs:[3,4,5]},
 {title:'把大张量切成小块',chapter:'第二章 · 开发基础',time:45,slot:'15:45—16:30',tag:'泛化 Tiling',original:'泛化 Tiling 设计、核函数实践。',goal:'解释核间分工、核内分块与尾块处理。',points:[['先分核，再分块','Tiling 将输入规模和硬件约束转化为核函数可用的切分信息。核间分配工作量，核内再按可容纳的数据量分块处理。'],['整数除法不是完整方案','不能整除时必须明确剩余元素由哪个核、哪个块负责。检查每个元素恰好被处理一次，且不发生越界。'],['内存预算需要一起算','输入、输出、临时数据以及多缓冲都会占用局部存储。教学中的元素分块计算不是可直接使用的硬件参数，仍需按对应 API 验证对齐和数据类型要求。']],exercise:'纸面练习：把 1000 个元素分给 3 个核，可采用 334、333、333；写出每核起始位置 0、334、667。再设计每核内部的分块与尾块策略，核对覆盖范围。',refs:[2,3,4]},
 {title:'完成一个 Vector 算子',chapter:'第二章 · 开发基础',time:60,slot:'16:30—17:30',tag:'从实现到验收',original:'Vector 算子开发实践。',goal:'完成一个自定义算子的构建、调用与输出核对。',points:[['把需求写成输入输出约定','建议从逐元素操作开始，先写清形状、数据类型、计算公式和输出要求。不要在正确性尚未验证时先追求性能。'],['使用独立参考结果核对','主机侧计算参考输出，与设备侧结果比较。浮点数应设定合适的绝对/相对误差；测试中应包含可整除和不可整除的输入规模。'],['形成可以复现的交付','保留源代码、环境版本、构建执行说明、输入数据、输出核对和失败案例。网页的“已完成”是自我记录，不代表设备端自动验收通过。']],exercise:'建议实现一个简单 Vector 算子。至少验证常规输入、尾块输入和包含零/负值的输入，记录参考结果与实际误差。',refs:[1,2,3]}
];
export const tasks = ['画出并解释软硬件架构图','在真实环境跑通入门示例并保存日志','解释 Add 的搬运、计算、写回流程','完成 Tiling 切分与尾块练习','完成自定义算子并核对输出'];
export const quiz = [
 {q:'CANN 在软件栈中的主要位置是？',options:['只负责显示训练曲线','连接上层 AI 框架与昇腾 AI 硬件','代替张量存储数据'],answer:1,why:'CANN 承接框架需求并服务底层 AI 处理器，算子开发是其中的重要能力。',module:0},
 {q:'描述张量时，应首先确认什么？',options:['仅文件名称','仅变量名','形状、数据类型与数据含义'],answer:2,why:'形状影响元素数量与索引，数据类型影响存储和运算。名称本身不能表达这些约束。',module:0},
 {q:'Kernel 直调中，哪项通常是 Host 的工作？',options:['准备资源、发起调用并读取结果','执行每个 Vector 指令','代替所有核内同步'],answer:0,why:'Host 组织调用及资源生命周期；Device 核函数负责分配给它的数据计算。',module:1},
 {q:'构建成功后，是否就可以认为算子正确？',options:['可以，编译器会验证所有输入','不可以，还需要执行并核对输出','只要程序没有打印错误即可'],answer:1,why:'构建不能证明计算结果正确。应执行样例并使用独立参考结果验证。',module:2},
 {q:'Add 入门样例的数据流程是？',options:['计算 → 搬入 → 写回','写回 → 计算 → 搬入','搬入 → 计算 → 写回'],answer:2,why:'先准备局部输入，再调用计算 API，最后将局部结果搬回全局内存。',module:3},
 {q:'TQue 和 TBuf 的主要区别是？',options:['TBuf 可直接替代所有队列同步','TQue 提供入队/出队，TBuf 用于临时存储','两者都只能保存主机文件'],answer:1,why:'TQue 用队列组织阶段间的数据流；TBuf 没有 EnQue/DeQue 队列语义。TPipe 可为两者分配存储。',module:3},
 {q:'输入长度无法被核数整除时，应怎么做？',options:['直接丢弃余数','让每个核都处理完整输入','设计余数分配并验证不越界、不遗漏'],answer:2,why:'泛化 Tiling 需要明确尾块策略，确保每个有效元素恰好被处理一次。',module:4},
 {q:'浮点算子验收时，哪个方法更合理？',options:['与参考实现比较，并设定合理误差','只查看运行耗时','只测试一种可整除形状'],answer:0,why:'浮点计算可能存在舍入差异，应结合数据类型确定误差标准，并覆盖尾块等边界场景。',module:5}
];
export const timetable = [['09:00—10:15','第一章：AI、算子、CANN 与 NPU','75 分钟'],['10:15—10:30','课间休息','15 分钟'],['10:30—11:30','第一章：Ascend C 基本概念与练习','60 分钟'],['11:30—13:45','原课表无课程','—'],['13:45—14:30','第二章：章节介绍与 Hello world','45 分钟'],['14:30—14:45','课间休息','15 分钟'],['14:45—15:30','第二章：编程范式、API 与 Add','45 分钟'],['15:30—15:45','课间休息','15 分钟'],['15:45—16:30','泛化 Tiling 设计、核函数实践','45 分钟'],['16:30—17:30','Vector 算子开发实践','60 分钟']];
