'use client';
import { useState } from 'react';
import { Table,TableHeader,TableHead,TableBody,TableRow,TableCell } from '@/components/ui/table';
import { ArrowRight, ArrowUpRight, BookOpen, CheckCircle2, Lightbulb } from 'lucide-react';
import { lessons,readings } from './lessons';

export function logicalTiling(n:number,cores:number,tile:number) {
 if(!Number.isInteger(n)||!Number.isInteger(cores)||!Number.isInteger(tile)||n<1||n>1000000||cores<1||cores>64||cores>n||tile<1||tile>16384)return null;
 const q=Math.floor(n/cores),r=n%cores;
 return Array.from({length:cores},(_,k)=>{const start=k*q+Math.min(k,r),length=q+(k<r?1:0);return {k,start,end:start+length,length,full:Math.floor(length/tile),tail:length%tile};});
}
function LearningTable({headers,rows}:{headers:string[];rows:string[][]}){return <div className="tutorial-table"><Table><TableHeader><TableRow>{headers.map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row,i)=><TableRow key={i}>{row.map((cell,j)=><TableCell key={j}>{cell}</TableCell>)}</TableRow>)}</TableBody></Table></div>;}
function AddWalkthrough(){const [step,setStep]=useState(0);const names=['准备全局输入','CopyIn · 搬入','Compute · 计算','CopyOut · 写回'];const desc=['Host 已准备 16 个 half 元素的输入。下方只展开前 4 项；输出还没有可验证结果。','将 x、y 的本块数据搬入局部缓冲，并经输入队列交给计算阶段。全局输入保持原值。','读取局部输入，逐元素计算 1+3、-2+2、0+(-1)、4+0.5。结果此时位于局部输出缓冲中。','结果从局部输出搬回全局输出。此时才有可供 Host 在正确同步后取回的本块结果。'];return <div className="learning-lab"><div className="lab-heading"><h4>跟着一块数据走一遍</h4><span>逻辑演示 · 无 NPU 调用</span></div><div className="step-buttons">{names.map((x,i)=><button key={x} onClick={()=>setStep(i)} aria-pressed={step===i} className={step===i?'active':''}>{i+1}. {x}</button>)}</div><p aria-live="polite">{desc[step]}</p><LearningTable headers={['存储位置','x / y','z']} rows={[[ 'Global Memory','x: [1, -2, 0, 4, …]\ny: [3, 2, -1, 0.5, …]',step===3?'[4, 0, -1, 4.5, …]':'尚未写回'],['Local Memory',step===0?'尚未搬入':step>=2?'输入已消费，可归还缓冲':'x、y 已就绪',step<2?'尚未计算':step===2?'[4, 0, -1, 4.5, …]':'结果已搬出，可归还缓冲']]} /><div className="lab-actions"><button disabled={step===0} onClick={()=>setStep(step-1)}>上一步</button><b>{step+1} / 4</b><button disabled={step===3} onClick={()=>setStep(step+1)}>下一步 <ArrowRight size={15}/></button></div><small>为便于阅读只展示部分数值；不表示硬件时序，也不测量性能。</small></div>;}
function TilingLab(){const [n,setN]=useState(1000),[k,setK]=useState(3),[t,setT]=useState(128);const rows=logicalTiling(n,k,t);const aligned=rows&&t%16===0&&rows.every(x=>x.start%16===0&&x.length%16===0);return <div className="learning-lab"><div className="lab-heading"><h4>自己算一次逻辑 Tiling</h4><span>half · 三路双缓冲</span></div><p>修改输入，观察核间区间与核内尾块。以下是数学计算，不是已通过硬件验证的执行参数。</p><div className="tiling-inputs"><label>有效元素 N<input type="number" min="1" max="1000000" value={n} onChange={e=>setN(Number(e.target.value))}/></label><label>逻辑核数 K<input type="number" min="1" max="64" value={k} onChange={e=>setK(Number(e.target.value))}/></label><label>块长 T（元素）<input type="number" min="1" max="16384" value={t} onChange={e=>setT(Number(e.target.value))}/></label></div>{!rows?<p role="alert" className="error">请输入整数：N 为 1–1,000,000，K 为 1–64 且不大于 N，T 为 1–16,384。</p>:<><div className="tiling-summary" aria-live="polite"><span>总覆盖 <b>{rows.reduce((a,r)=>a+r.length,0)} 项</b></span><span>三路双缓冲 <b>{3*2*t*2} 字节</b></span></div><LearningTable headers={['核','全局区间 [起,止)','长度','满块','尾长']} rows={rows.map(r=>[String(r.k),`[${r.start}, ${r.end})`,String(r.length),String(r.full),String(r.tail)])}/><p className={aligned?'lab-success':'lab-warning'}>{aligned?'这些逻辑起点和长度满足本演示的 32 字节粒度检查。仍需核对实际芯片、API、物理容量和 UB 预算。':'存在不满足本演示 32 字节粒度的起点或长度。不要直接按此区间调用普通连续 DataCopy；需要合法尾块接口或真实分配的填充方案。'}</p></>}<small>公式采用均衡余数分配；缓冲预算未包含临时数据、框架及其他占用。</small></div>;}
export function DetailedLesson({module}:{module:number}){const lesson=lessons[module];return <div className="detailed-lesson"><div className="lesson-guide"><div><BookOpen size={19}/><b>这一节怎么学</b><span>{lesson.sections.length} 个小节 · 每节附练习解析</span></div><p><strong>先备知识：</strong>{lesson.prerequisite}</p><ul>{lesson.outcomes.map(x=><li key={x}>{x}</li>)}</ul><small>以下为补充自学教程，非培训原讲义。代码为教学片段或改写；具体版本与出处标在小节末尾。</small></div><nav className="lesson-toc" aria-label="本模块小节目录">{lesson.sections.map((x,i)=><a key={x.title} href={`#lesson-${module}-${i}`}><span>{String(i+1).padStart(2,'0')}</span>{x.title}</a>)}</nav>{lesson.sections.map((section,i)=><section className="tutorial-section" id={`lesson-${module}-${i}`} key={section.title}><div className="tutorial-heading"><span>{String(i+1).padStart(2,'0')}</span><h3>{section.title}</h3></div>{section.paragraphs.map(p=><p key={p}>{p}</p>)}{section.table&&<LearningTable {...section.table}/>} {section.code&&<div className="code-example"><div className="code-label"><span>{section.code.language}</span><b>{section.code.label}</b></div><pre tabIndex={0} aria-label={section.code.label}><code>{section.code.text}</code></pre><ol className="code-notes">{section.code.notes.map(x=><li key={x}>{x}</li>)}</ol></div>}{section.example&&<div className="worked-example"><b><Lightbulb size={17}/>{section.example.title}</b><p>{section.example.text}</p></div>}{section.pitfall&&<div className="pitfall"><b>容易混淆</b><p>{section.pitfall}</p></div>}{module===3&&i===4&&<AddWalkthrough/>}{module===4&&i===5&&<TilingLab/>}<div className="section-question"><span>停下来，自己想一想</span><p>{section.question.prompt}</p><details><summary>查看参考答案与解释</summary><p>{section.question.answer}</p></details></div>{section.refs&&<div className="tutorial-refs">{section.refs.map(key=>{const r=readings[key];return <a key={key} href={r.url} target="_blank" rel="noreferrer"><span>{r.title}<small>{r.version}</small></span><ArrowUpRight size={15}/></a>;})}</div>}</section>)}<div className="module-assignment"><div className="tutorial-heading"><CheckCircle2 size={22}/><h3>{lesson.assignment.title}</h3></div><ol>{lesson.assignment.steps.map(x=><li key={x}>{x}</li>)}</ol><h4>做到这些，再标记模块完成</h4><ul>{lesson.assignment.criteria.map(x=><li key={x}>{x}</li>)}</ul><p>将你的推导、回答或真实运行记录写入下方模块笔记；需要设备验证的部分应单独记录运行环境与结果。</p></div></div>;}
