export type Reading = { title: string; version: string; url: string };
export type Section = {title:string; paragraphs:string[]; table?:{headers:string[];rows:string[][]}; example?:{title:string;text:string}; code?:{language:string;label:string;text:string;notes:string[]}; pitfall?:string; question:{prompt:string;answer:string}; refs?:string[]};
export type Lesson = {prerequisite:string;outcomes:string[];sections:Section[];assignment:{title:string;steps:string[];criteria:string[]}};
export const readings:Record<string,Reading> = {
 overview:{title:'CANN 架构与开发入口',version:'商用版 8.2.RC1',url:'https://www.hiascend.com/document/detail/zh/canncommercial/82RC1/index/index.html'},
 architecture:{title:'AI Core 硬件架构',version:'商用版 8.0.0 · 英文',url:'https://www.hiascend.com/document/detail/en/canncommercial/800/opdevg/Ascendcopdevg/atlas_ascendc_10_0008.html'},
 kernel:{title:'核函数定义、调用与逻辑核',version:'商用版 8.5.0 · 语法参考',url:'https://www.hiascend.com/document/detail/zh/canncommercial/850/opdevg/Ascendcopdevg/atlas_ascendc_10_0014.html'},
 hello:{title:'HelloWorld 官方入门',version:'社区版 8.2.RC1',url:'https://www.hiascend.com/document/detail/zh/CANNCommunityEdition/82RC1/opdevg/Ascendcopdevg/atlas_ascendc_10_0003.html'},
 add:{title:'Add 直调核函数源代码',version:'Ascend/samples · v1.0-8.1.RC1.alpha001',url:'https://gitee.com/ascend/samples/blob/v1.0-8.1.RC1.alpha001/operator/ascendc/0_introduction/3_add_kernellaunch/AddKernelInvocationNeo/add_custom.cpp'},
 init:{title:'TPipe::InitBuffer',version:'商用版 8.2.RC1',url:'https://www.hiascend.com/document/detail/zh/canncommercial/82RC1/API/ascendcopapi/atlasascendc_api_07_0110.html'},
 api:{title:'Ascend C API 分类与入口',version:'社区版 8.2.RC1.alpha003',url:'https://www.hiascend.com/document/detail/zh/CANNCommunityEdition/82RC1alpha003/API/ascendcopapi'},
 programming:{title:'编程接口概述',version:'社区版 8.2.RC1.alpha003',url:'https://www.hiascend.com/document/detail/zh/CANNCommunityEdition/82RC1alpha003/opdevg/Ascendcopdevg/atlas_ascendc_10_0018.html'},
 tiling:{title:'Tiling 与 Kernel 实现的关系',version:'社区版 8.2.RC1.alpha003',url:'https://www.hiascend.com/document/detail/zh/CANNCommunityEdition/82RC1alpha003/opdevg/Ascendcopdevg/atlas_ascendc_10_0031.html'},
 copy:{title:'DataCopy 连续搬运及对齐约束',version:'商用版 7.0.RC1 · 对齐案例参考',url:'https://www.hiascend.com/doc_center/source/zh/canncommercial/70RC1/operatordev/Ascendcopdevg/atlasascendc_api_07_0143.html'},
 pipeline:{title:'流水优化的原理',version:'官方技术文章 · 2024-08-19',url:'https://www.hiascend.com/developer/techArticles/20240819-1'},
 debugging:{title:'Kernel 直调调测流程',version:'社区版 8.0.RC3.alpha003',url:'https://www.hiascend.com/document/detail/zh/CANNCommunityEdition/80RC3alpha003/devaids/auxiliarydevtool/atlasascendebug_16_0020.html'},
 ai:{title:'AI、机器学习与深度学习',version:'Google Cloud · 基础概念补充',url:'https://cloud.google.com/discover/deep-learning-vs-machine-learning?hl=zh-CN'},
 history:{title:'人工智能及其发展脉络',version:'AWS · 基础概念补充',url:'https://aws.amazon.com/cn/what-is/artificial-intelligence/'}
};
export const lessons: Lesson[] = [
{
 prerequisite:'不要求昇腾经验。先会读数组、加法和乘法即可；张量与硬件术语会在下面解释。',
 outcomes:['把一次 AI 推理拆成模型、算子和张量','算出张量元素数与存储量','说明 CANN、Atlas、AI Core 和 Vector 的职责'],
 sections:[
 {title:'AI 最终为什么会变成一串算子？',paragraphs:['人工智能是让计算机完成识别、预测、生成等任务的一类方法。机器学习从数据中调整模型参数；深度学习是其中使用多层神经网络的方法。三者不是并列的三种硬件，也不是“代码越多就越智能”。','可以把发展脉络记成三条主线：早期的规则与符号推理，依赖数据的统计学习，以及利用多层神经网络的深度学习。它们并非互相完全替代。深度学习和生成式模型扩大了计算规模，也让矩阵运算、逐元素运算和数据搬运的效率变得重要。','以图像分类为例：图片先变成数字数组，模型反复进行卷积或矩阵乘、加偏置、激活等运算，最后得到类别分数。训练会根据误差调整参数；推理使用已经学到的参数产生输出。算子开发者通常实现其中某一步数学运算，而不是在 Kernel 里重新训练整个模型。'],example:{title:'从一句业务需求落到数学计算',text:'“判断图片里有没有猫”是任务；神经网络是模型；模型中的 y = max(0, W × x + b) 可拆为矩阵乘、加法、ReLU 三类运算。把这些操作实现为适合硬件执行的代码，就是理解算子开发的起点。'},pitfall:'“AI 算子必须自己学习”是误解。Add 算子的规则就是相加，参数学习通常发生在模型训练流程中。',question:{prompt:'语音识别是算子吗？如果不是，它和 Add 有什么关系？',answer:'语音识别是完整任务。模型把声音数据变成张量，再由多个算子组成计算过程；Add 可能用于加偏置或连接分支结果，是任务内部的一种基础计算。'},refs:['ai','history']},
 {title:'张量：先看形状，再看数据类型',paragraphs:['张量可以先理解为“带形状的多维数组”。标量没有轴，向量有一个轴，矩阵有两个轴。shape = [2, 3] 表示两行三列，元素数是 2 × 3 = 6；rank 是轴数，这里为 2。rank 和元素数不能混用。','dtype 决定一个元素的表示方式和字节数。float32 通常占 4 字节，float16/half 占 2 字节。相同形状在不同 dtype 下需要的内存不同，运算精度与支持范围也可能不同。这里只计算连续、无额外填充数据的有效载荷。','算子代码常把连续多维数据当作一维数据处理。对按行连续存储的 [2, 3] 矩阵，坐标 [r, c] 对应线性下标 r × 3 + c。但改变“形状描述”和真正重新排列内存不是一回事；有 stride、转置或特殊格式时不能直接套用这个公式。'],table:{headers:['属性','例子','写 Kernel 时要确认'],rows:[['shape','[2, 3]','处理多少个元素，维度如何映射'],['dtype','float16 / float32','一项占几字节，计算 API 是否支持'],['layout / stride','按行连续','线性偏移是否有效，是否需要重排'],['有效载荷','6 × 2 = 12 字节','申请空间还可能需要考虑对齐/填充']]},example:{title:'手算一次存储量',text:'一张 NCHW 格式的图像，shape = [1, 3, 4, 4]，共有 48 个元素。float32 的有效数据为 192 字节；float16 为 96 字节。改变 dtype 不会把 48 个元素变成 24 个元素。'},question:{prompt:'shape = [4, 8] 的 float16 张量有多少元素、多少有效字节？按行连续时 [2, 3] 的线性下标是多少？',answer:'32 个元素，64 字节。线性下标是 2 × 8 + 3 = 19；若从字节地址计算偏移，则为 19 × 2 = 38 字节。注意：元素偏移 19 和字节偏移 38 是两个单位。'},refs:['api']},
 {title:'算子的名字不是完整规格',paragraphs:['算子是一个输入到输出的计算约定。写代码之前，必须明确输入数量、形状、dtype、输出形状、数学公式以及支持的边界。名称 Add 只说明“加”，并没有自动决定是否支持广播、不同 dtype 混合或非连续内存。','逐元素运算让每个位置独立计算；归约运算把多个元素合成较少元素；矩阵运算组合两个维度的乘加；数据变换可能改变布局。计算之间有没有数据依赖，直接决定能不能把任务分到不同核。','本教程最先实现的 Add 限定为两个同形状、同 dtype、连续存储的输入，输出也同形状。先让这个范围内的行为正确，再单独扩展广播或尾块。缩小范围不是遗漏，而是把第一版契约写清楚。'],table:{headers:['类别','例子','对并行的影响'],rows:[['逐元素','z[i] = x[i] + y[i]','不同 i 可独立分配'],['归约','s = Σ x[i]','局部结果还需要合并'],['矩阵','C = A × B','要考虑多个维度和数据复用'],['数据变换','Transpose / Cast','要注意布局或类型转换']]},example:{title:'把 Add 规格写成可测试的约定',text:'x = [1, -2, 0, 4]，y = [3, 2, -1, 0.5]，则 z = [4, 0, -1, 4.5]。这组数适合检查下标和负数处理；它是数学例子，不意味着仅 4 个元素可以直接使用任意数据搬运接口。'},question:{prompt:'x 的形状是 [2, 3]，y 是 [3]，这个入门 Add 能直接接受吗？',answer:'按本教程的第一版约定不能，因为没有实现广播。若需要广播，必须先定义 y 如何对应每一行，再改写索引/搬运方案并增加测试。不能仅修改输出 shape 就宣称支持。'},refs:['programming']},
 {title:'CANN 在哪一层？Atlas 又是什么？',paragraphs:['从上到下看：应用提出任务，框架组织模型计算，CANN 提供面向昇腾的软件能力，驱动与固件配合硬件完成实际执行。Ascend C 是 CANN 中面向自定义算子开发的编程方式；AscendCL 是主机侧使用的运行时接口体系。','Atlas 指昇腾相关产品形态与系列，不是一个可在程序里调用的 API。拿到服务器后应记录具体设备/芯片型号，配套驱动、固件和 CANN 版本，再选择对应样例。只知道“有 Atlas 机器”不足以确定所有接口都能使用。','Kernel 直调是学习中较短的一条路径：主机程序直接组织核函数调用，不必先完成模型框架接入。它适合观察输入、计算、输出的闭环，但不能自动等同于一个已注册到任意框架的工程化算子。'],table:{headers:['层次','解决的问题','本课与它的关系'],rows:[['应用 / 模型框架','用什么模型解决任务','理解算子从哪里来'],['CANN / Ascend C','如何表达并执行计算','编写 Device 核函数'],['AscendCL','如何管理运行时资源和调用','编写 Host 主程序'],['驱动、固件、昇腾设备','如何实际执行并管理硬件','确保环境配套可用']]},example:{title:'顺着一次调用走一遍',text:'主机读取 x、y → 申请设备内存并复制输入 → 在 stream 上发起 Add → 等待完成 → 复制 z 回主机 → 对比参考结果 → 释放资源。每个箭头都对应一个需要检查的边界。'},question:{prompt:'为什么在笔记中仅记录“CANN 已安装”不够？',answer:'无法复现兼容性问题。至少记录精确 CANN 版本、驱动/固件版本、芯片型号、操作系统及样例分支；同名 API 在不同版本或芯片上可能有不同约束。'},refs:['overview']},
 {title:'AI Core：计算快，还要把数据送到位',paragraphs:['理解硬件时先抓住分工：Vector 负责矢量计算，Cube 面向矩阵计算，Scalar 承担标量与控制工作，MTE 负责数据搬运。具体芯片可能采用耦合或分离架构，不能把某一代硬件图当作所有 NPU 的统一布局。','对本课的 Vector 路径，用一条线记忆即可：GM（全局内存）→ UB（局部缓冲）→ Vector 计算 → UB → GM。数据通常先进入局部存储，计算 API 才能使用它。GM 空间较大，局部缓冲有限，所以不能一律把整个输入一次搬进去。','有两层并行：核间把不同数据段交给不同逻辑核；核内把搬运和计算安排到相应执行单元。并行不是“没有先后”，计算仍然要等输入就绪，写回仍然要等结果就绪。后续的队列和 Tiling 就是在描述这些约束。'],example:{title:'为什么一个加法也值得分块？',text:'设一项数据占 2 字节，x、y、z 各有 1,000,000 项，仅三份有效载荷就有 6,000,000 字节。局部存储不能按输入规模无限增长；将它切成固定大小的块，处理完一块再复用空间，才是可扩展的做法。'},pitfall:'GM、UB 是存储位置；GlobalTensor、LocalTensor 是编程中的访问抽象。声明一个 GlobalTensor 不等于在设备上新申请一块全局内存。',question:{prompt:'“有多个执行单元，所以可以先 Compute 再 CopyIn”错在哪里？',answer:'同一数据块的 Compute 依赖 CopyIn 的结果。不同块的搬运和计算可以在条件允许时重叠，但同一块的数据依赖仍需通过同步保证。'},refs:['architecture','pipeline']}
 ],assignment:{title:'画一张真正能讲明白的架构图',steps:['画出应用/框架、CANN、驱动固件、昇腾硬件四层。','在主机侧标注数据准备、调用与验证；在设备侧标注 GM、UB、Vector。','用 Add 的一组输入解释数据经过每一层时发生了什么。'],criteria:['能区分模型、算子和张量。','能说清 Ascend C 与 AscendCL 的不同作用。','能解释为什么需要搬运、分块与同步。']}
},
{
 prerequisite:'已理解张量、元素数/字节数和 GM/UB；最好了解 C++ 函数、指针和类的基础写法。',outcomes:['读懂核函数入口中的限定符','通过逻辑核编号定位本核的数据','解释异步调用、stream 与资源生命周期'],
 sections:[
 {title:'先把 Host 与 Device 两边的程序分开',paragraphs:['Host 通常是负责控制流程的 CPU 侧程序；Device 是执行加速计算的 NPU。它们不是同一个内存空间里随意互相调用的两个普通函数。主机上的数组地址不能不经处理就当作设备输入地址使用。','Host 创建运行环境、分配设备缓冲、复制输入、提交任务、等待完成并读取结果。Device 的 Kernel 只根据传入地址和切分参数处理数据。主机端文件读取或普通容器操作不应直接搬进核函数。','先画出资源的所有者：谁申请、谁使用、何时不再使用、谁释放。核函数被提交后仍可能在运行，此时释放设备输入会破坏它尚未完成的访问。'],table:{headers:['资源 / 对象','所在位置','典型职责'],rows:[['xHost / yHost','主机内存','准备输入、生成参考结果'],['xDevice / yDevice / zDevice','设备全局内存','承载核函数的输入输出'],['LocalTensor','核内局部存储的访问对象','给 Vector 计算提供局部数据'],['stream','运行时任务序列','组织提交顺序，提供同步点']]},example:{title:'一个变量名无法保证位置正确',text:'即使把 CPU 数组命名为 xDevice，它仍然是 CPU 数组。要看地址来自哪个内存申请接口，以及输入是否按正确的方向复制到了设备缓冲。'},question:{prompt:'主机里 xHost 有 64 个 half 元素，设备缓冲只申请 64 字节，够吗？',answer:'不够。64 × 2 = 128 字节才是有效载荷。应按元素数乘以 dtype 字节数申请，并确保复制长度、核函数理解的数据类型一致。'},refs:['programming','hello']},
 {title:'拆开核函数声明中的每一个符号',paragraphs:['核函数入口在普通 C/C++ 函数语法上添加了设备执行限定。__global__ 标明核函数入口，__aicore__ 说明在 AI Core 侧执行；__gm__ 表示指针指向 Global Memory。GM_ADDR 是常用的统一入口地址类型。','extern "C" 用于采用 C 链接方式，避免按 C++ 重载规则修饰函数名；它不是“在 CPU 上执行”的标记。inline 是 C++ 的函数说明，不能代替设备限定符，也不意味着整个算子只运行一次。','入口地址可以统一以字节指针表达，进入实现后再按实际 dtype 解释。若输入文件实际写的是 float32，而 Kernel 把它当 half 读取，字节会被错误解读，偏移也会错误，即使编译成功也无法得到正确结果。'],code:{language:'C++ / 语法示意',label:'入口框架，不是完整可运行算子',text:'extern "C" __global__ __aicore__\nvoid lesson_add(GM_ADDR inputA, GM_ADDR inputB, GM_ADDR output) {\n    // 按本核范围绑定输入输出，再处理局部数据块\n}',notes:['lesson_add 是本教程自拟名称；函数体还没有实现计算。','入口只接收地址，不会自动申请输入输出，也不会自动复制主机数组。','本课沿用 8.x 文档中的 SIMD 核函数概念，不混入新版本 SIMT 线程语法。']},question:{prompt:'extern "C"、__aicore__、__gm__ 分别回答哪三个问题？',answer:'extern "C" 回答“采用什么链接命名方式”；__aicore__ 回答“函数在哪类执行空间运行”；__gm__ 回答“指针指向哪类内存”。它们解决不同问题。'},refs:['kernel']},
 {title:'同一段代码，怎样让不同核做不同的事？',paragraphs:['发起多核调用时，各核执行相同的核函数代码，入口参数也相同。区别来自核内获取的逻辑编号。GetBlockIdx() 给出当前编号，GetBlockNum() 给出本次配置的 Block 数；它们不是每个数据元素的编号。','先看完全可整除的例子：N = 64，配置 4 个逻辑核，则每核处理 16 个元素。第 k 个核的起点为 16 × k。核 0 处理 [0,16)，核 1 处理 [16,32)，以此类推。半开区间 [a,b) 包含 a、不包含 b，长度恰好是 b-a。','blockDim 是执行配置，不是输入长度，也不是保证性能提升的开关。本课纯 Vector 示例先使用简单的核编号模型；不同芯片、混合算子和资源限制下应按对应文档确认配置方式。'],table:{headers:['逻辑核 k','元素区间','half 字节起点'],rows:[['0','[0, 16)','0'],['1','[16, 32)','32'],['2','[32, 48)','64'],['3','[48, 64)','96']]},example:{title:'指针偏移为什么要先确认类型？',text:'half* 指针加 16，前进的是 16 个 half，即 32 字节；uint8_t* 指针加 16，仅前进 16 字节。先转换到实际类型再按元素偏移，与按字节地址加偏移不是同一种写法。'},pitfall:'每个核都从 x[0] 开始处理，会重复计算同一段，甚至多核写入同一输出区域。必须同时检查输入与输出偏移。',question:{prompt:'N=96、核数=3 且均分，第 2 号核的范围是什么？float32 的字节偏移又是多少？',answer:'每核 32 个元素，第 2 号核从 64 开始，范围 [64,96)。float32 字节偏移为 64 × 4 = 256 字节。核编号从 0 开始，2 号核是第三个核。'},refs:['api','kernel']},
 {title:'提交、完成与释放，是三个时刻',paragraphs:['内核调用符中的 stream 表示任务提交到哪个流。核函数调用是异步的：Host 发起任务后可以继续执行，不意味着设备计算已经结束。主机读取输出或回收设备资源前，要建立正确的完成依赖。','在本课串行入门流程中，提交核函数后使用流同步等待，检查返回结果，再取回输出。后续更复杂的重叠执行可以减少不必要的等待，但必须有等价的依赖控制，不能简单删除同步来“优化”。','初始化、设备选择、流创建、内存申请、复制和同步都可能失败。真正的主机程序应检查返回码，并按已经成功申请的资源进行清理。教学流程图只表达顺序，不代替这些错误处理。'],code:{language:'流程伪代码',label:'按生命周期理解主机逻辑',text:'初始化运行时 → 选择设备 → 创建流\n申请 x、y、z 的设备缓冲\n复制 x、y：Host → Device\n提交 kernel 到 stream\n等待该 stream 的任务完成，检查结果\n复制 z：Device → Host → 核对参考值\n释放缓冲 → 销毁流 → 重置设备 → 结束运行时',notes:['同步是验证“提交完成”和“计算完成”之间差别的关键步骤。','发生错误时也要清理已申请的资源，不应继续使用无效指针。']},question:{prompt:'为什么“先提交 Kernel，马上释放 xDevice，再等待”不正确？',answer:'Kernel 可能尚未读取 xDevice，释放会使任务访问已失效的资源。应确保所有使用该缓冲的任务完成后再释放。'},refs:['hello','kernel']},
 {title:'直调程序由哪些文件组成？',paragraphs:['最小工程通常至少包含核函数文件、主机调用文件和构建配置。Kernel 文件表达设备计算；main 文件管理主机流程；构建配置告诉编译工具目标芯片、头文件和库所在位置。只有一段 __aicore__ 代码，还不是完整工程。','阅读官方样例时不要按文件长度盲读。先从 main 找入口，再找到调用封装，接着进入 Kernel，最后回看构建脚本。这条顺序能让你知道每个函数是谁调用、输入从哪里来、结果被谁验证。','CPU 调测和 NPU 执行是不同的验证路径。CPU 调测可帮助检查逻辑，不能当作上板性能测量；本网页中的数据演示又是第三类，只帮助理解步骤，不会编译或执行 Ascend C。'],table:{headers:['文件角色','需要找到的内容'],rows:[['main.cpp','设备选择、资源申请、调用、同步、验证、清理'],['核函数 .cpp','入口参数、本核偏移、搬入、计算、写回'],['CMakeLists.txt','目标芯片和工具链/依赖配置'],['运行脚本 / README','实际编译入口、运行模式、预期产物']]},question:{prompt:'只把设备端 .cpp 交给普通 g++，就能完成 NPU 上板验证吗？',answer:'不能。NPU 代码需要对应的 Ascend C 工具链与构建配置，主机侧还要链接相应运行时。CPU 调测也有自己的样例路径与接口，并不是任意 g++ 命令都可以识别 <<<>>>。'},refs:['hello','debugging']}
 ],assignment:{title:'在纸面上走完一次调用',steps:['画 Host 与 Device 两列，在正确位置放入输入、设备缓冲、局部张量、输出。','为 N=96、3 个核写出所有半开区间和 float32 字节偏移。','标出提交、等待、输出验证与资源释放的位置。'],criteria:['三个区间不重叠、不遗漏。','能解释元素偏移和字节偏移。','任何设备资源都在使用结束后释放。']}
},
{
 prerequisite:'已读懂 Host/Device 和异步调用。执行本模块需要匹配的昇腾开发环境；没有环境也能完成代码阅读与故障定位练习。',outcomes:['读懂 HelloWorld 的两侧代码','按官方工程配置实际芯片型号并运行','分清配置、编译、运行、验证四个阶段'],
 sections:[
 {title:'开始前先建立一份环境记录',paragraphs:['本节的 HelloWorld 流程依据 CANN 社区版 8.2.RC1 官方入门页。它是可供对照的明确版本，不代表培训指定版本，也不建议为了本网页盲目升级环境。如果实际安装不同版本，优先切换到对应版本的官方样例。','至少记录五项信息：实际芯片型号，驱动与固件，CANN Toolkit 版本，操作系统/CPU 架构，样例来源与分支。开发机用于编译，运行机需要能使用目标设备；二者若不是同一台，文件和依赖的准备需要分别完成。','在实际昇腾服务器上用 npu-smi info 检查设备信息。soc_version 的写法按该版本官方页面从设备信息映射，A3 与非 A3 的查询方式有区别，不能把另一台机器的 Ascend910B… 字符串直接复制过来。'],table:{headers:['检查项','写入笔记的内容','作用'],rows:[['设备','npu-smi 输出及设备 ID','确认有可访问的目标设备'],['配套版本','驱动 / 固件 / Toolkit 完整版本','排查二进制和接口兼容'],['样例','官方 URL、分支或提交','让别人能取到同一份代码'],['运行方式','NPU / CPU 调测','防止混淆验证结论'],['构建参数','实际 soc_version 和安装路径','避免默认值指向错误芯片']]},question:{prompt:'本地 Windows 笔记本没有昇腾设备，看到这段教程后应该做什么？',answer:'先阅读代码并准备环境记录表；需要上板时使用组织方提供或自己已配置的昇腾环境。不要在笔记本中勾选“真实环境运行通过”，也不要把浏览器演示当作设备运行。'},refs:['hello','overview']},
 {title:'设备端只有一句打印，也能看懂调用边界',paragraphs:['HelloWorld 不需要读写输入张量，目标是证明核函数入口可被构建并调用。下面是按官方语法改写的教学片段，改了函数名和输出文本；它必须放入匹配的官方工程结构中，不能单独当作完整构建文件。','真正位于设备侧的部分是 hello_lesson 函数。launch_lesson 在构建好的调用路径中使用 <<<>>> 发起执行。blockDim 决定执行配置，nullptr 是此处保留参数的常见写法，stream 来自主机程序创建的流。'],code:{language:'C++ / Ascend C',label:'HelloWorld 教学改写 · 语法参照 8.2.RC1',text:'#include "kernel_operator.h"\n\nextern "C" __global__ __aicore__ void hello_lesson() {\n    AscendC::printf("Lesson kernel reached\\n");\n}\n\nvoid launch_lesson(uint32_t blockDim, void* stream) {\n    hello_lesson<<<blockDim, nullptr, stream>>>();\n}',notes:['第 1 行引入 Ascend C 核函数接口。','第 3–5 行定义实际设备入口，打印是这里的业务逻辑。','第 7–9 行封装发起调用；它不会自动创建 stream。','复制教学改写时，主机侧声明与调用名称也必须一起匹配。']},pitfall:'主机侧 std::cout 或 printf 输出正常，并不能证明 Device Kernel 被执行。检查打印来自哪一个文件、哪一种执行空间。',question:{prompt:'看到“Lesson kernel reached”后，就能认为 Add 数据搬运和数值计算都正确吗？',answer:'不能。HelloWorld 只验证最小调用链。它没有输入输出张量，不能覆盖 Add 的内存申请、搬运、索引和精度问题。'},refs:['hello']},
 {title:'主机侧的关键不是打印，而是生命周期',paragraphs:['先从主机 main 找到初始化、设备选择和 stream 创建。调用封装只需要传入核配置与 stream；随后主机等待该流完成，最后释放资源。这样才能把“发起调用”闭合成“完成并收尾”。','官方入门代码为了展示流程会压缩错误处理。自己动手时，应逐个检查 aclError 返回值是否成功；如果流没有创建成功，不能继续向它提交 Kernel。首次失败位置比最后一行连带错误更有诊断价值。'],table:{headers:['顺序','接口 / 操作','你要回答的问题'],rows:[['1','aclInit','运行时是否初始化成功？'],['2','aclrtSetDevice','设备 ID 是否存在、可用？'],['3','aclrtCreateStream','stream 是否创建成功？'],['4','调用 launch_lesson','名称与参数是否和设备封装匹配？'],['5','aclrtSynchronizeStream','异步任务是否完成，返回码是什么？'],['6','aclrtDestroyStream / aclrtResetDevice / aclFinalize','资源是否按正确生命周期释放？']]},example:{title:'从错误链找到第一处失败',text:'假设创建 stream 失败，后面 Kernel 提交和流同步也报错。应先修复流创建问题，而不是同时改写 Kernel、Tiling 和计算公式。一次只消除一个根因，保留失败日志用于复现。'},question:{prompt:'把流同步移到销毁流之后，会出现什么逻辑问题？',answer:'等待操作需要有效的流对象。销毁之后再同步不满足资源生命周期要求；应先等待任务完成，确认状态，再销毁流。'},refs:['hello','debugging']},
 {title:'在真实环境中完成配置、构建和运行',paragraphs:['打开本节末尾的官方 HelloWorld 页面，从页面中的样例工程链接取得完整工程，阅读其 README。先核对 CMake 配置中的芯片型号和 CANN 安装路径，再执行该工程的脚本。本节不把不同版本的安装命令拼成一个通用脚本。','以下是官方 8.2.RC1 入门页采用的运行入口模板。soc_version 必须先替换为真实设备所对应的值，路径也应是你实际下载的 HelloWorld 工程。对于组织方提供的环境，优先使用已经配好的路径和版本。','执行时保留完整终端输出和退出码。先看编译是否产生可执行文件，再看调用是否完成、是否出现设备侧的打印。多核打印的输出顺序不保证按核号排序；验证是否有对应输出，不要依赖固定行顺序。'],code:{language:'Bash / 命令模板',label:'仅在匹配的官方工程与真实开发环境中执行',text:'# 在昇腾服务器确认设备信息\nnpu-smi info\n\n# 进入官方 HelloWorld 工程目录后，先替换此变量\nsoc_version="替换为官方规则对应的实际芯片型号"\nbash run.sh -v "$soc_version"',notes:['npu-smi 需要安装并可访问驱动；网页不会执行这些命令。','此参数形式来自链接中的 8.2.RC1 页面；其他样例的 run.sh 参数未必相同。','原版样例的输出文本为 Hello World!!!；上面的教学改写使用不同文本，二者不要混淆。']},question:{prompt:'为什么不能把“示例用了 8 个核”理解为“任何环境都必须填 8”？',answer:'这是该入门示例的配置，不是所有芯片或算子的固定要求。核数应符合实际硬件、运行模式与对应版本文档；改动后要重新验证预期输出。'},refs:['hello']},
 {title:'按阶段排错，并写出可复现的验收结果',paragraphs:['配置阶段的问题通常表现为找不到编译器、头文件或依赖库；编译阶段会指出语法、类型或符号不匹配；运行阶段可能是设备、运行时或内存问题；验证阶段则检查是否确实完成预期行为。先确定失败发生在哪一层，能少做很多无关修改。','保留一份最小可复现记录：原样例来源、环境、你的改动、完整命令、首次错误、退出码和观察到的输出。不要只截取“运行失败”四个字。成功记录也要注明是 NPU 上板还是 CPU 调测。'],table:{headers:['现象','优先检查','不要急着做'],rows:[['找不到 kernel_operator.h','环境变量、安装路径、构建入口','随意复制一份头文件进项目'],['<<<>>> 语法报错','是否使用正确设备编译链/模式','把内核调用改成普通 CPU 函数'],['链接找不到函数','声明、定义、名称、链接目标','假定设备已经坏了'],['程序结束却没有预期输出','执行路径、同步返回码、打印位置','立即勾选任务已完成']]},question:{prompt:'运行记录只写“HelloWorld 已通过”缺了什么？',answer:'缺了环境版本、样例分支、运行模式、命令和输出证据。补上这些才能确认通过的是哪条路径，并让其他人复现。'},refs:['debugging']}
 ],assignment:{title:'提交一份 HelloWorld 运行记录',steps:['填写环境记录表，打开并阅读匹配版本的完整官方工程。','逐个定位设备入口、调用封装、stream 创建和同步。','在真实环境运行并保存命令、退出码、设备侧输出；无环境时标记“待上板”。'],criteria:['能区分主机输出与设备输出。','运行模式和版本明确。','成功与失败都能定位到配置/编译/运行/验证阶段。']}
},

{
 prerequisite:'已掌握核函数、数据偏移与异步调用。接下来以已标明版本的官方 Add 样例为阅读对象；代码片段是教学改写，省略的工程部分需保留官方实现。',outcomes:['用具体数值算出每核和每次循环的工作量','解释队列生命周期及三个计算阶段','区分元素个数、缓冲字节数和队列深度'],
 sections:[
 {title:'先算明白样例参数，再读循环',paragraphs:['先不看 API，把 Add 写成 z[i] = x[i] + y[i]。本节阅读的官方样例有 16,384 个 half 元素，使用 8 个核，因此每核分到 2,048 个元素。Kernel 内各自处理自己的这一段，而不是每个核都处理全部输入。','该样例设置 TILE_NUM=8、BUFFER_NUM=2，并用二者共同确定单次处理长度：2,048 ÷ 8 ÷ 2 = 128。实际 Process 循环为 8 × 2 = 16 次。变量名 TILE_NUM 不能脱离代码公式直译成“只循环 8 次”。','固定参数样例隐含了“可以整除”的前提。你不能只把总长度改成 1,000 而保留其余公式，就认为完成了泛化；整数除法可能丢掉未处理的元素。'],table:{headers:['量','本样例数值','含义'],rows:[['TOTAL_LENGTH','16,384','全部输入元素数'],['BLOCK_LENGTH','2,048','每个核的元素数'],['TILE_LENGTH','128','每轮处理的元素数'],['loopCount','16','本核循环次数'],['单轮输入 x 字节数','256','128 个 half × 2 字节']]},example:{title:'追踪第 3 号核的第 5 轮',text:'本核起点 = 3 × 2,048 = 6,144；本轮偏移 = 5 × 128 = 640；所以处理全局区间 [6,784, 6,912)。这是第 4 个核的第 6 轮，因为编号从 0 开始。'},question:{prompt:'为什么 8 核 × 16 轮 × 128 个元素恰好覆盖输入？如果循环只写 8 轮，会怎样？',answer:'8 × 16 × 128 = 16,384。只循环 8 轮时每核仅处理 1,024 个元素，总共处理 8,192 个，会遗漏每核负责区域的后半段。'},refs:['add']},
 {title:'TPipe、TQue 和 TBuf 各管什么？',paragraphs:['TPipe 负责为框架中的缓冲资源进行管理与初始化。TQue 在两个阶段之间传递局部张量，并配合框架建立通信和同步；TBuf 适合当前计算过程中使用的临时空间，没有 EnQue/DeQue 的队列交接。','队列模板里的 depth 与 InitBuffer 的 num 是不同概念。depth 描述允许连续入队的深度；num 描述分配多少块缓冲。简单的逐块生产/消费可以使用深度 1，而双缓冲分配两块存储。不要因为它们在某个样例里都写 2，就把它们当成同一参数。','初始化时的长度通常按字节表示，而 DataCopy/Add 的计数形式按元素表示。本例每块有 128 个 half，所以为一块输入缓冲申请 256 字节。x、y、z 三个队列各分配两块，合计有效缓冲量为 3 × 2 × 256 = 1,536 字节，尚未计入其他资源。'],code:{language:'C++ / Ascend C',label:'教学配置：深度 1 与两块缓冲不是同一概念',text:'AscendC::TPipe pipe;\nAscendC::TQue<AscendC::TPosition::VECIN, 1> inputQueue;\n// 位于初始化逻辑内：2 块，每块 128 个 half\npipe.InitBuffer(inputQueue, 2, 128 * sizeof(half));',notes:['片段把声明和初始化放在一起便于阅读；在工程中按对应作用域放置。','这里只展示一个输入队列，还需要另一个输入与一个输出队列。','官方样例采用的模板深度可能不同，修改前先核对具体入队顺序。']},pitfall:'“TBuf 是不用释放的 TQue”并不准确。TBuf 用于局部临时计算空间，不能拿来替代跨阶段队列的数据交接和同步。',question:{prompt:'InitBuffer(q, 2, 256) 中的 2 和 256 分别是什么单位？若每项为 half，每块能放几项？',answer:'2 是缓冲块数量；256 是每块的字节长度。half 占 2 字节，因此每块能容纳 128 项，共两块。这与 TQue 模板 depth 的含义不同。'},refs:['init','api','programming']},
 {title:'CopyIn：取得空闲缓冲，再把输入搬进来',paragraphs:['先用 AllocTensor 从队列的缓冲资源中取得可用 LocalTensor。此时“有了局部空间”不等于“里面已经有本轮输入”。接着 DataCopy 将本轮全局输入搬进该局部空间，再 EnQue 交给下一阶段。','CopyIn 的全局偏移 = 本核起点 + 本轮起点。如果 GlobalTensor 在初始化时已经绑定到本核起点，那么循环内部只加本轮偏移，不能再次叠加本核起点。x 与 y 要使用一致的有效区间。','下面的片段只展示 x 的一条输入通路，y 要执行对称的步骤。128 是元素个数，不是字节数；这里使用 half 时对应 256 字节。实际接口还需要满足芯片、地址和对齐约束。'],code:{language:'C++ / Ascend C',label:'单路搬入片段 · 假定全局张量已绑定本核范围',text:'auto tileX = xQueue.AllocTensor<half>();\nAscendC::DataCopy(tileX, xGlobal[round * 128], 128);\nxQueue.EnQue(tileX);',notes:['AllocTensor：取得空闲局部缓冲的访问对象。','DataCopy：安排从本核第 round × 128 项开始搬入。','EnQue：把这份数据交给消费阶段，不是再复制一次整个数组。']},question:{prompt:'如果 AllocTensor 后直接 EnQue，没有 DataCopy，下一阶段会得到什么？',answer:'没有得到本轮所需的可靠输入。分配局部空间不等于初始化数据；内容可能是旧值或未定义值。应把对应数据正确搬入再交接。'},refs:['add','copy']},
 {title:'Compute 与 CopyOut：把生命周期闭合',paragraphs:['Compute 先从两个输入队列 DeQue，取到本轮就绪的数据，再为输出申请 LocalTensor。调用 Add 完成逐元素求和后，把输出 EnQue；输入不再被这轮计算使用时，分别 FreeTensor 归还给队列管理。','CopyOut 从输出队列 DeQue，把结果搬回本核对应的全局输出位置，再 FreeTensor。对队列中取出的张量，应有相应的生命周期收尾；仅把变量离开 C++ 作用域，并不能代替这些框架操作。','这里的 Alloc/Free 是局部队列缓冲的使用与归还，不是每轮都在主机上重新申请/释放整块 Device 全局内存。两个层次必须区分，才能理解复用为什么有效。'],code:{language:'C++ / Ascend C',label:'计算与写回片段 · xQueue/yQueue/zQueue 已初始化',text:'// Compute\nauto a = xQueue.DeQue<half>();\nauto b = yQueue.DeQue<half>();\nauto result = zQueue.AllocTensor<half>();\nAscendC::Add(result, a, b, 128);\nzQueue.EnQue(result);\nxQueue.FreeTensor(a);\nyQueue.FreeTensor(b);\n\n// CopyOut\nauto readyResult = zQueue.DeQue<half>();\nAscendC::DataCopy(zGlobal[round * 128], readyResult, 128);\nzQueue.FreeTensor(readyResult);',notes:['Add 的前一个张量参数是输出，后两个是输入。','计算计数 128 应与本轮搬运长度及缓冲容量一致。','写回位置仍使用本核 GlobalTensor 加本轮偏移。','这是阅读片段，不包含完整类、初始化、入口和 Host 工程。']},pitfall:'DeQue 不是 FreeTensor。前者把就绪数据交给消费者使用，后者是在用完后归还缓冲；少一个可能导致资源无法正确复用。',question:{prompt:'为什么不能在 CopyIn 入队之后立刻释放那份输入，再让 Compute 取它？',answer:'数据还要被后续阶段消费，过早归还可能使同一缓冲被复用覆盖。应按生产、交接、消费、归还的顺序管理所有权。'},refs:['add','api']},
 {title:'三段流水与双缓冲：顺序写法不等于硬件完全串行',paragraphs:['源代码中常看到 CopyIn → Compute → CopyOut 的顺序，但这些工作由不同执行单元处理。借助框架同步，后续块的搬入可能与当前块的计算重叠；能否重叠及收益取决于依赖、缓冲和实际执行开销。','双缓冲提供两组可轮换的空间：一组供当前阶段使用，另一组准备后续数据。它解决“新数据覆盖正在使用的旧数据”的资源冲突，但不会取消输入就绪和结果就绪的依赖，也不是把所有速度自动提高两倍。','学习时先用一块数据追踪正确性，再看多块之间的重叠。下面的交互只展示一块数据的逻辑阶段，不显示硬件时序，不是 NPU 执行结果。'],example:{title:'把流水想成三项工作，而不是三份答案',text:'对同一个块，输入必须先就绪，结果才能计算，计算完成后才可写回。对不同块，搬运与计算在依赖允许时可能交错。仅看 Python 或浏览器演示的快慢，不能推断 Ascend C 性能。'},question:{prompt:'“用了 BUFFER_NUM=2，所以运行时间一定减半”为什么不成立？',answer:'如果瓶颈在计算、搬运无法重叠、数据规模太小或额外同步较多，双缓冲收益可能有限。必须在正确的设备与计时范围内实测，不能由参数值推断性能。'},refs:['pipeline']},
 {title:'读代码时用四条不变量检查自己',paragraphs:['第一，覆盖范围正确：所有有效元素都被处理，且输出没有被多个核意外重复写。第二，容量一致：每轮元素数不超过为输入输出分配的局部容量。第三，单位一致：元素、字节和 DataBlock 不混用。第四，生命周期闭合：先生产、后消费、用完归还。','检查 API 时不要只搜函数名。要确认当前重载、源/目的位置、dtype、count 单位、地址对齐和长度对齐。普通连续 DataCopy 的某些版本/通路要求搬运量按 32 字节对齐；未满足时不能指望它自动“帮你处理剩余元素”。','本课 128 个 half = 256 字节，便于满足相应示例的块长度要求。换成 17 个 half = 34 字节后，必须重新检查接口约束。数学公式仍然正确，不等于数据搬运就已经合法。'],question:{prompt:'把 Add 的计算计数从 128 改为 256，却仍只给输出分配 256 字节的 half 缓冲，哪里不匹配？',answer:'256 个 half 需要 512 字节；原缓冲只有 256 字节，即 128 个元素。计算范围超过容量，应同步调整切分、搬运、输出容量，并核对局部内存预算。'},refs:['copy','init']}
 ],assignment:{title:'给官方 Add 写一份带数字的阅读笔记',steps:['计算并写出每核元素数、单轮长度、循环次数和缓冲字节数。','选一个非零核号、非零轮号，写出全局半开区间。','给 x、y、z 分别画出 Alloc → EnQue → DeQue → Free 的使用关系。','解释为什么更改输入长度必须连同切分和搬运约束一起检查。'],criteria:['能从公式证明全部元素被覆盖。','能定位输入归还与输出归还的位置。','不会混淆 TQue 深度和缓冲数量。']}
},
{
 prerequisite:'已经能计算固定 Add 样例的偏移、循环次数和局部容量。这里先练数学切分，再讨论让它满足真实硬件接口的条件。',outcomes:['推导可处理余数的核间分配公式','计算每核完整块、尾块与内存预算','区分逻辑有效长度和实际申请/搬运长度'],
 sections:[
 {title:'Tiling 是一组约定，不只是除法',paragraphs:['Tiling 的任务是把输入规模与硬件约束转成执行计划：多少个逻辑核参与、每核从哪里开始、处理多少项、每次搬多少、最后剩多少、局部缓冲占多少。Host 和 Kernel 必须用相同的定义解释这些值。','固定样例可以把参数写成常量。要支持不同形状，就需要让切分随输入变化，并通过明确的参数传给核函数。工程化 Tiling 结构和直调参数的传递形式可能不同，本节先把共同的数学关系学清楚。','一个计划至少要通过三项检查：区间覆盖 [0,N)，区间之间没有意外重叠，所有搬运和计算都满足容量与接口限制。负数、零长度、核数过多等边界也必须有明确处理约定。'],table:{headers:['符号','单位','本教程含义'],rows:[['N','元素','总有效长度'],['K','逻辑核','计划使用的核数'],['start[k]','元素偏移','第 k 核的起点'],['length[k]','元素','第 k 核的有效工作量'],['T','元素','每轮目标块长'],['B / S','块数 / 字节','缓冲数量 / 每项字节数']]},question:{prompt:'一个核收到 start=128、length=64，使用半开区间写出它的范围。结束位置属于它吗？',answer:'范围是 [128,192)，共 64 项；192 不属于这个核。半开区间便于相邻核无重叠衔接，下一段可以从 192 开始。'},refs:['tiling']},
 {title:'不能整除时，把余数明确分出去',paragraphs:['一种均衡的逻辑分配是先算 q = N // K、r = N % K。前 r 个核各处理 q+1 项，其余核处理 q 项。这样负载最多相差 1，而且总数 K×q+r 恰好是 N。','对应起点公式是 start[k] = k×q + min(k,r)。长度是 length[k] = q + (k<r ? 1 : 0)。起点包含前面所有核多拿的余数，因此不能仍用 k×q 作为所有核的起点。','以 N=1000、K=3 为例，q=333、r=1，三个核分别处理 334、333、333 项，起点 0、334、667。注意：这只是逻辑划分。334 个 half 的字节边界未必符合你选择的搬运接口，后面仍要处理对齐。'],code:{language:'Python / 可在普通 CPU 上验证的数学算法',label:'核间区间计算，不调用 NPU',text:'def logical_ranges(n, cores):\n    assert n > 0 and 1 <= cores <= n\n    q, r = divmod(n, cores)\n    return [(k*q + min(k, r), q + (k < r))\n            for k in range(cores)]\n\n# 结果为 (起点, 长度)，不是 (起点, 终点)\nprint(logical_ranges(1000, 3))',notes:['第 k 核终点 = 起点 + 长度。','如果 N<K，可以减少参与核数，或明确处理空工作核；本算法选择要求 K≤N。','运行这段 Python 只能验证切分数学，不能验证 DataCopy 的合法性。']},question:{prompt:'N=10、K=3 时，各核起点和长度是什么？若起点仍用 k×3，哪里错了？',answer:'长度 4、3、3；起点 0、4、7；区间 [0,4)、[4,7)、[7,10)。使用 k×3 会得到 0、3、6，从而产生重叠并遗漏最后的元素。'},refs:['tiling']},
 {title:'核内分块：满块与尾块分别计算',paragraphs:['对某个核的 L 个有效元素，设块长 T。完整块数为 L // T，尾块长度为 L % T。只有尾块长度大于 0 时才额外处理一块；不要因为“最后一轮”就固定再加一个完整块。','例如 L=334、T=128：两块完整块各 128 项，尾块 78 项。若该核全局起点为 0，则三块逻辑区间分别是 [0,128)、[128,256)、[256,334)。另一核必须加上它自己的 start[k] 才得到全局范围。','最常见错误是尾轮仍执行 T 个元素的搬运和计算。当实际内存没有申请填充区时，这会访问越界。反过来，只循环 L//T 次会丢弃尾部。尾块不是“自动发生”，而是要明确编码的分支或填充方案。'],example:{title:'换个核再算一次',text:'N=1000、K=3、T=128。第 1 号核 start=334、L=333：满块 [334,462)、[462,590)，尾块 [590,667)，尾长 77。三个区间连起来恰好覆盖该核的 [334,667)。'},question:{prompt:'L=256、T=128，需要几轮？尾长为 0 时再处理一轮有什么问题？',answer:'恰好 2 轮，没有尾块。再处理一轮会从元素 256 开始访问本核范围之外的数据，造成越界或侵入下一核的区域。'},refs:['tiling']},
 {title:'对齐：正确的数学区间，还不是可直接搬运的区间',paragraphs:['普通 DataCopy 的部分连续搬运重载按 32 字节粒度约束长度，具体以当前版本、数据通路和 dtype 为准。以这种规则为例，half 每项 2 字节，则块长需是 16 个元素的倍数；float32 则是 8 个元素的倍数。核的起点地址也需要单独核对。','处理不对齐可以选择版本与芯片支持的非对齐搬运接口，或者在主机侧真实申请填充空间。无论选择哪条路，都不能只把数字向上取整，却仍访问原来较短的分配区域。计算掩码也不能自动修复已经越界的数据搬运。','对逐元素 Add，一种便于入门的保守方案：N=1000，但为 x、y、z 各申请 1024 个 half，输入后 24 项补 0；用 4 核均分，每核 256 项，再用 128 项分块。核起点和每轮长度满足这个示例的 32 字节粒度；最后只验证前 1000 个输出。该方案会增加存储与计算，并不适合直接套用到所有归约算子。'],table:{headers:['长度含义','这个 Add 例子','使用位置'],rows:[['逻辑有效长度','1000','输出校验与业务语义'],['物理分配长度','1024','实际申请和输入填充'],['每核物理长度','256','4 核划分'],['单轮长度','128','每核 2 轮'],['忽略的填充输出','末尾 24 项','不计入业务结果']]},pitfall:'“补齐”必须同时改变真实内存申请、输入初始化与访问范围，不能只改变 Kernel 的循环上限。',question:{prompt:'N=17 个 half，只申请 34 字节，然后把搬运长度上取整为 32 个元素，安全吗？',answer:'不安全。32 个 half 需要 64 字节，原申请只有 34 字节。必须真实分配并初始化足够的空间，或使用已核验支持该非对齐场景的接口与策略。'},refs:['copy','init']},
 {title:'局部内存预算：块长并非越大越好',paragraphs:['设每个元素 S 字节，块长 T，x、y、z 三个队列各有 B 个缓冲，则仅这三路有效缓冲就占 3×B×T×S 字节。还要加临时空间、对齐填充以及其他资源，不能直接把芯片的全部 UB 容量都分给输入。','若给三路数据预留 12,288 字节，B=2、S=2，则按简化预算 T≤12,288÷12=1024。这个结果是预算上限示例，不是任何芯片的推荐参数；实际仍要检查可用容量和接口限制。','块太小会增加循环和交接开销；块太大可能导致空间不足，也会改变流水机会。正确做法是先满足约束和正确性，再在真实环境里测量，而不是从“更大”推导“更快”。'],example:{title:'加一个临时缓冲会怎样？',text:'若同一预算中再加入一份 T×S 的临时数据，总量变为 (3B+1)×T×S。B=2、S=2 时是 14T 字节。12,288÷14 向下取整为 877；再按 half 的 16 元素粒度向下取整为 864。对齐与预算要同时满足。'},question:{prompt:'T=512、B=2、dtype=half，三路队列的有效缓冲是多少字节？再加一份同长度临时缓冲呢？',answer:'三路队列为 3×2×512×2 = 6,144 字节；临时缓冲为 512×2 = 1,024 字节；合计 7,168 字节。实际还要考虑框架与其他占用。'},refs:['init']},
 {title:'让 Host 与 Kernel 对同一份参数达成一致',paragraphs:['Host 根据实际输入生成切分参数，Kernel 按同样单位解释这些参数。如果 Host 传“字节数”，Kernel 却当作“元素数”，数据越大越容易越界。参数名称最好明确使用 elementCount、tileElements、byteSize 这类含义。','泛化时不要同时改十个地方。先保留固定配置作为基线，再将总长度参数化，再处理不能整除的核间分配，最后处理核内尾块和接口对齐。每一步都有独立的输入输出测试，才容易定位新引入的错误。','下面的计算器帮助检查逻辑分工和预算。它会明确标出对齐问题，不会把数学计算结果当作已通过的 NPU Tiling 参数。'],question:{prompt:'Host 认为 tileLength=256 字节，Kernel 按 256 个 half 处理，双方相差多少？',answer:'Host 的 256 字节只容纳 128 个 half；Kernel 想处理 256 个 half，即 512 字节，相差一倍。必须统一字段单位，而不是只在某一侧扩大缓冲来掩盖问题。'},refs:['tiling']}
 ],assignment:{title:'给 1000 项 Add 设计两个方案',steps:['先写出 3 核均衡逻辑切分、每核 T=128 的满块与尾块。','指出该方案在普通连续搬运规则下需要补充的对齐处理。','再写出真实分配 1024 项、4 核均分、每块 128 项的填充方案。','说明输出只比较前 1000 项，并计算三路双缓冲预算。'],criteria:['所有有效索引被覆盖一次。','物理分配范围覆盖每一次实际搬运。','Host 与 Kernel 的参数单位完全一致。']}
},
{
 prerequisite:'已读懂 Add 三阶段与 Tiling。本模块是补充实践项目，沿用已核对的 API 概念，实际编译运行要在匹配的官方工程中完成。',outcomes:['先写契约再改 Kernel','给一个 Vector 算子建立参考结果和边界测试','区分逻辑正确、上板正确与性能改进'],
 sections:[
 {title:'先交付基础 Add，再挑战两步 Vector 计算',paragraphs:['基础验收目标是完成同形状、同 dtype、连续输入的 Add，并从 Host 发起调用后核对输出。若这条链路没有通过，先不要同时加入复杂广播、归约或矩阵运算。','通过基础版后，可以做一个明确的小扩展：计算 z = (x + y) + y。它仍然逐元素，但有一个中间结果，正好用于练习临时缓冲和多步 Vector 计算。本项目是本网页的学习建议，不是原培训公布的题目。','先规定浮点语义。本练习采用 half 输入、中间结果和输出，每一步加法后都有 half 精度舍入；它不应被默认为“先用高精度算 x+2y，最后只舍入一次”。数学等价不保证浮点逐步结果逐位相同。'],table:{headers:['契约项','本练习约定'],rows:[['输入','x、y 为同形状、连续 half 数据'],['输出','与输入同形状的 half 数据'],['计算顺序','先 t=half(x+y)，再 z=half(t+y)'],['第一版长度','从已满足切分和对齐的长度开始'],['扩展长度','按已说明的填充或合法尾块策略处理'],['特殊数','首轮只测试有限正常值；NaN/Inf 行为另定规则']]},example:{title:'先用能准确表示的小数手算',text:'x=[1,-2,0,4]，y=[3,2,-1,0.5]。第一步 t=[4,0,-1,4.5]，第二步 z=[7,2,-2,5]。将这四项重复成满足约束的输入长度，便于肉眼核对与定位下标错误。'},question:{prompt:'为什么参考实现不能无条件写成 x+2*y？',answer:'代数上相同，但本练习规定先做 x+y 并舍入，再加 y 再舍入。改变运算顺序和中间精度可能改变浮点结果；参考实现必须匹配约定的语义。'},refs:['programming','add']},
 {title:'把需求落实到每个工程位置',paragraphs:['输入输出数量没有变化，因此可以保留两路输入队列和一路输出队列。增加的是计算阶段中的临时张量：先保存第一步相加的结果，再用它与 y 做第二次加法。因为中间数据不跨 CopyIn/CopyOut 阶段交接，TBuf 是合适的学习对象。','初始化时给临时缓冲分配 tileElements×sizeof(half) 字节；计算阶段从 TBuf 获取相应类型的 LocalTensor。x、y 必须在两次计算都结束其使用后再归还；特别是 y 会被读取两次，不能在第一步之后就释放。','主机端同时更新参考输出，保留输入生成、资源管理、调用和同步流程。只改 Kernel 但仍拿 Add 的参考结果做比较，会把本来正确的新功能判为错误。'],code:{language:'C++ / Ascend C',label:'两步计算示意 · 合入匹配版本工程后才能运行',text:'// 类成员：临时计算缓冲\nAscendC::TBuf<AscendC::TPosition::VECCALC> temporary;\n\n// Init 内：tileElements 是一块的元素数\npipe.InitBuffer(temporary, tileElements * sizeof(half));\n\n// Compute 内：输入已出队，输出已分配\nauto intermediate = temporary.Get<half>();\nAscendC::Add(intermediate, xLocal, yLocal, tileElements);\nAscendC::Add(zLocal, intermediate, yLocal, tileElements);\n// 然后入队输出，并按生命周期归还输入',notes:['该片段展示新增部分，缺少的类成员、输入出队、输出入队和主机逻辑要保留。','临时空间按一个块的容量配置，并计入 UB 预算。','同一 Vector 阶段的两步运算仍需遵循对应 API 的依赖与使用约束；不应据此删掉原有队列同步。']},question:{prompt:'为什么这里的 intermediate 不必再建一个输入队列？',answer:'它只在当前计算阶段内用于传递中间结果，没有承担 CopyIn 到 Compute 等阶段之间的交接。TBuf 提供临时存储即可；若改变了跨阶段结构，则需要重新设计同步。'},refs:['init','api']},
 {title:'独立参考结果：先核对形状，再核对数值',paragraphs:['参考实现应与设备实现分开，让主机按明确公式计算期望结果。比较前先检查文件长度、元素数量、shape 和 dtype；否则“比较通过”可能只是某种广播或错误读法造成的假象。','本练习对有限正常值，使用逐步 half 舍入生成参考：先把 half 输入转为 float32 做加法，再转回 half；第二步同样处理。这样把每一步的舍入位置写明白。对于溢出、非正规数或 NaN/Inf，需要另设测试与平台语义判断，不声称这个简化参考覆盖所有特殊行为。','验证可使用 |actual-reference| ≤ atol + rtol×|reference|。atol 处理接近 0 的值，rtol 随参考值大小缩放。容差必须事先根据 dtype、运算和题目标准确定，不能为让失败变成功而一再放宽。'],code:{language:'Python / NumPy',label:'本项目的独立参考与校验片段，读取真实输出后使用',text:'import numpy as np\n\nx = np.array([1, -2, 0, 4], dtype=np.float16)\ny = np.array([3, 2, -1, 0.5], dtype=np.float16)\nt = (x.astype(np.float32) + y.astype(np.float32)).astype(np.float16)\nexpected = (t.astype(np.float32) + y.astype(np.float32)).astype(np.float16)\n\ndef verify(actual, expected, atol, rtol):\n    if actual.shape != expected.shape or actual.dtype != expected.dtype:\n        return False\n    a = actual.astype(np.float32)\n    b = expected.astype(np.float32)\n    if not (np.isfinite(a).all() and np.isfinite(b).all()):\n        return False  # 特殊数不属于本轮验收范围\n    return bool(np.allclose(a, b, atol=atol, rtol=rtol))',notes:['actual 必须来自设备真实输出，不能把 expected 自己当作 actual。','atol、rtol 没有在这里硬编码，先按验收标准确定。','若使用填充输入，先取实际有效长度再比较，并保留物理输出以排查越界。']},question:{prompt:'actual 是 [4]、expected 是 [4,4,4]，为什么不能直接让比较函数尝试广播？',answer:'输出形状已经不符合算子契约。即使广播后数值相同，也不能证明设备写出了三个正确元素；应先判定形状不匹配而失败。'},refs:['debugging','numpy']},
 {title:'一张测试矩阵，比一次随机通过更有价值',paragraphs:['优先用容易手算的数据确认公式，再用边界长度检查索引和尾块，最后用固定随机种子扩展数据覆盖。只测试全零输入容易掩盖错偏移、漏写或把输出清零的错误。','选择长度时，围绕核数与块长设计：恰好一块、刚少于一块、刚多于一块、多核均分、不能被核数整除。若当前版本只支持对齐长度，就应明确拒绝其他输入，或先执行你已实现的合法填充方案。','定位失败时记录第一个错误位置、最大绝对误差及其索引。错误集中在每块边界时先查偏移/尾块；所有元素都偏差类似时先查公式、dtype 或参考语义。诊断规律只是线索，仍需逐项验证。'],table:{headers:['输入场景','想抓到的问题','应留下的证据'],rows:[['小整数、零、正负混合','公式和符号错误','手算结果与实际输出'],['T-1、T、T+1','块边界与尾块错误','物理分配和逻辑长度'],['不能被 K 整除','核间余数与偏移错误','每核区间表'],['固定种子有限随机值','一般数值问题','种子、容差、最大误差'],['多次连续调用','旧数据残留或资源管理问题','重复次数及每次结果']]},question:{prompt:'N=1024 成功、N=1025 最后一项错误，你应该先查哪里？',answer:'先查最后一块长度、最后一个核的有效长度、填充与物理申请是否一致，以及输出是否只比较了有效范围。不要首先盲目扩大浮点容差，因为这种分布更像范围问题。'},refs:['debugging']},
 {title:'正确性通过后，才讨论性能',paragraphs:['CPU 调测能帮助验证逻辑和定位错误；NPU 上板才能确认实际设备路径；性能评估还要定义计时范围。浏览器中的演示和切分计算器没有任何上板性能含义。','如果只用 Host 时钟包住异步提交动作，测到的主要是提交开销，任务可能还没结束。即使在外部同步后计时，结果也可能包含主机等待、数据传输和其他开销，应清楚区分端到端时间与 Kernel 时间。','对比版本时固定硬件、输入形状、dtype 和计时方法，重复运行并记录波动。先建立基线，再一次改变块长、缓冲或核数中的一个因素。用官方调测工具观察执行单元与搬运活动，才能解释瓶颈。'],example:{title:'一份诚实的结果表应该写什么？',text:'例如列出：输入 N 与 dtype、设备/CANN 版本、运行模式、误差判定、计时范围、重复次数、基线与改动后耗时。没有真实测量时填写“未测”，不要用网页演示生成一个看似精确的微秒数。'},question:{prompt:'只比较两次“点运行到页面显示结果”的时间，能证明双缓冲优化有效吗？',answer:'不能。页面交互不是设备计时，可能还包括网络和界面开销。需要在一致的 NPU 环境中测量明确的算子时间，并确认两版正确性都通过。'},refs:['pipeline','debugging']},
 {title:'最后交付一个能被别人复现的算子',paragraphs:['完成定义不应只是“我机器上跑过”。把代码、环境、输入生成、参考计算、构建命令、运行命令和结果放在一起，让别人能重复你的验证。失败案例同样有价值，它说明当前支持范围在哪里。','使用本网页的模块笔记记录实际过程，实践清单只在满足相应条件后勾选。没有真实环境时可以完成设计、代码阅读与数学验证，并清晰标为“待上板”；不要把这些学习成果包装成设备执行通过。'],table:{headers:['交付项','最低内容'],rows:[['README','目标公式、形状/dtype、支持范围、环境版本'],['实现','Host、Kernel、构建配置与切分规则'],['测试','输入生成、独立参考、比较规则、边界用例'],['记录','真实命令、退出码、输出、误差和已知问题']]},question:{prompt:'如果同学换一个输入长度就失败，这个项目还算完全完成吗？',answer:'要看写下的支持契约。若声称泛化到该长度，就未完成；若第一版明确只支持特定对齐范围，应拒绝不支持的输入并说明限制，再把泛化作为下一步。'},refs:['debugging']}
 ],assignment:{title:'完成 Add 基线或两步 Vector 扩展',steps:['写清输入输出契约，并先手算一组数据。','在匹配官方工程中实现或阅读对应 Kernel 和 Host 调用。','核对切分、对齐、缓冲容量和生命周期。','准备独立参考与边界测试，在真实环境执行并记录证据。','正确性通过后再测性能；没有测量就明确标注未测。'],criteria:['参考实现独立于设备输出。','边界形状不越界、不遗漏。','环境、版本、命令和测试结果可复现。','区分设计完成、CPU 调测与 NPU 上板三个状态。']}
}
];
readings.numpy = {title:'NumPy allclose 的比较规则',version:'NumPy 2.2 官方文档',url:'https://numpy.org/doc/2.2/reference/generated/numpy.allclose.html'};
