'use client';
import { useEffect, useRef, useState } from 'react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Checkbox } from '@/components/ui/checkbox';
import { Progress } from '@/components/ui/progress';
import { BookOpen, CalendarDays, Check, ArrowUpRight, ArrowRight, Code2, NotebookPen, ListChecks, RotateCcw, Cloud, GraduationCap } from 'lucide-react';
import { modules, sources, tasks, quiz, timetable } from './course';
import { DetailedLesson } from './detailed-lesson';
type Plan = {date:string;text:string;minutes:number;done:boolean};
type State = {done:number[];tasks:number[];notes:Record<string,string>;answers:(number|null)[];plan:Plan[];settings:{start:string;end:string;minutes:number}};
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function datePlus(date:string,n:number){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
const initial:State={done:[],tasks:[],notes:{},answers:Array(quiz.length).fill(null),plan:[],settings:{start:'',end:'',minutes:45}};
export default function Page(){
 const [s,setS]=useState<State>(initial),[view,setView]=useState('learn'),[active,setActive]=useState(0),[ready,setReady]=useState(false),[status,setStatus]=useState('正在读取本机学习记录…'),[error,setError]=useState(false),[notice,setNotice]=useState(''),[reviewOnly,setReviewOnly]=useState(false);
 const previousModule=useRef(active);
 useEffect(()=>{if(previousModule.current!==active){previousModule.current=active;document.getElementById('lesson-content')?.scrollIntoView({behavior:'smooth',block:'start'});}},[active]);
 const latest=useRef(s); latest.current=s;
 function load(){try{const raw=window.localStorage.getItem('ascend-c-learning-progress');const parsed=raw?JSON.parse(raw) as Partial<State>:{};const val:State={...initial,...parsed,notes:parsed.notes||{},answers:Array.isArray(parsed.answers)&&parsed.answers.length===quiz.length?parsed.answers:initial.answers,settings:{...initial.settings,...parsed.settings,start:parsed.settings?.start||today(),end:parsed.settings?.end||datePlus(today(),7)}};setS(val);setReady(true);setError(false);setStatus('已保存在本机浏览器');}catch{setReady(true);setError(true);setStatus('本机存储不可用，内容只保留在当前页面');}}
 function save(){try{window.localStorage.setItem('ascend-c-learning-progress',JSON.stringify(latest.current));setError(false);setStatus('已保存在本机浏览器');}catch{setError(true);setStatus('保存失败，内容仍在当前页面');}}
 useEffect(()=>{load();},[]);
 useEffect(()=>{if(!ready)return;const t=setTimeout(save,350);return()=>clearTimeout(t);},[s,ready]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();try{Promise.resolve(ctx.registerTool({name:'read_learning_progress',description:'读取当前学习模块完成情况与学习计划，不修改数据',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('此读取接口仅接受空对象');return {completedModules:latest.current.done,plan:latest.current.plan};}},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[]);
 function toggle(key:'done'|'tasks',id:number){if(!ready)return;setS(p=>({...p,[key]:p[key].includes(id)?p[key].filter(x=>x!==id):[...p[key],id]}));}
 function note(value:string){setS(p=>({...p,notes:{...p.notes,[active]:value}}));}
 const m=modules[active],percent=Math.round(s.done.length/modules.length*100),minutes=s.done.reduce((n,i)=>n+modules[i].time,0);
 function makePlan(){const {start,end,minutes:budget}=s.settings;if(!start||!end||end<start||!Number.isFinite(budget)||budget<10||budget>480){setNotice('请选择有效日期，每天安排 10–480 分钟。');return;}const days=Math.round((new Date(end+'T12:00:00').getTime()-new Date(start+'T12:00:00').getTime())/86400000)+1;if(days>366){setNotice('请将计划限制在一年内。');return;}const remaining=modules.map((x,i)=>({...x,i})).filter(x=>!s.done.includes(x.i));const total=remaining.reduce((n,x)=>n+x.time,0);if(total===0){setNotice('全部模块已完成，可前往复习回顾笔记和错题。');return;}if(days*budget<total){setNotice(`时间不足：剩余课程 ${total} 分钟，当前容量 ${days*budget} 分钟。每天至少需要 ${Math.ceil(total/days)} 分钟，或延后目标日期。`);return;}if(s.plan.length&&!window.confirm('重新生成会替换当前计划及其勾选状态，课程进度和笔记会保留。继续吗？'))return;const plan:Plan[]=[];let day=0,used=0;remaining.forEach(x=>{let left=x.time,part=1;while(left>0){if(used===budget){day++;used=0;}const count=Math.min(left,budget-used);plan.push({date:datePlus(start,day),text:x.title+(count<x.time?` · 第 ${part} 段`:''),minutes:count,done:false});left-=count;used+=count;part++;}});setS(p=>({...p,plan}));setNotice(`已按剩余 ${total} 分钟课程生成计划。实践与复习可另加条目；课时仅作自学估算。`);}
 function exportNotes(){const text=modules.map((x,i)=>`# ${x.title}\n${s.notes[i]||'暂无笔记'}`).join('\n\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));a.download='Ascend-C-学习笔记.md';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 return <div className="app"><header><a className="brand" href="/"><span className="brand-icon">A</span><span>Ascend C <b>学习工坊</b></span></a><div className="header-meta">CANN 挑战赛 · 赛前学习<span className="pill">Kernel 直调</span></div></header>
 <main><div className="intro"><div><div className="eyebrow">YOUR LEARNING WORKSPACE</div><h1>把算子开发，学得更清楚。</h1><p>从核心概念到第一个自定义算子，一步一步完成你的学习路径。</p></div><div className="save-area"><div role="status" className={error?'error':'save'}><Cloud size={17}/>{status}</div>{error&&<div><button onClick={save}>重试</button></div>}<small>无需登录 · 进度保存在当前浏览器</small></div></div>
 <div className="overview"><div className="progress-card"><div><span className="label">课程进度</span><strong>{percent}<small>%</small></strong></div><div className="progress-info"><Progress value={percent}/><span>{s.done.length} / 6 个模块已完成</span></div></div><div className="stat"><BookOpen/><div><b>5 小时 30 分</b><span>原课表授课时长</span></div></div><div className="stat"><Check/><div><b>{minutes} 分钟</b><span>已完成模块对应课时</span></div></div><div className="stat"><Code2/><div><b>{s.tasks.length} / 5 项</b><span>建议实践验收</span></div></div></div>
 <Tabs value={view} onValueChange={setView}><TabsList className="main-tabs" variant="line"><TabsTrigger value="learn"><BookOpen/>课程学习</TabsTrigger><TabsTrigger value="plan"><CalendarDays/>学习计划</TabsTrigger><TabsTrigger value="quiz"><GraduationCap/>概念自测</TabsTrigger><TabsTrigger value="practice"><ListChecks/>实践与复习</TabsTrigger><TabsTrigger value="schedule">原课表与资料</TabsTrigger></TabsList>
 <TabsContent value="learn"><div className="learning-grid"><section className="modules"><div className="section-title"><h2>学习路径</h2><span>06 MODULES</span></div>{modules.map((x,i)=><button key={i} className={'module '+(active===i?'selected':'')} onClick={()=>setActive(i)}><span className={'number '+(s.done.includes(i)?'completed':'')}>{s.done.includes(i)?<Check size={18}/>:String(i+1).padStart(2,'0')}</span><span><small>{x.chapter}</small><b>{x.title}</b><em>{x.time} 分钟 · {x.tag}</em></span>{active===i&&<ArrowRight size={17}/>}</button>)}<div className="tip"><NotebookPen size={20}/><p>边学边记<br/><span>用自己的话解释一次，比重复阅读更有帮助。</span></p></div></section>
 <article className="lesson" id="lesson-content"><div className="lesson-top"><span className="blue-label">模块 {String(active+1).padStart(2,'0')} / 06</span><span>{m.time} 分钟 · 原课表 {m.slot}</span></div><h2>{m.title}</h2><p className="goal">{m.goal}</p><div className="original"><b>原课程内容</b><p>{m.original}</p></div><DetailedLesson key={active} module={active}/><div className="note"><label htmlFor="module-note"><NotebookPen size={17}/>本模块笔记</label><textarea id="module-note" maxLength={12000} disabled={!ready} value={s.notes[active]||''} onChange={e=>note(e.target.value)} placeholder="记下你理解的概念、遇到的问题，或真实环境的执行日志…"/><small>停止输入后自动保存。资料版本详见各小节出处与“原课表与资料”。</small></div><div className="lesson-actions"><label className="check-label"><Checkbox checked={s.done.includes(active)} disabled={!ready} onCheckedChange={()=>toggle('done',active)}/>我已完成本模块学习</label><button className="primary" onClick={()=>{if(active<5)setActive(active+1);else setView('practice');}}>{active<5?'下一模块':'前往实践验收'}<ArrowRight size={17}/></button></div></article></div></TabsContent>
 <TabsContent value="plan"><section className="panel"><div className="section-title"><div><h2>按你的节奏安排学习</h2><p>以未完成模块的原课时为估算，可拆分到多天；实践与复习请预留额外时间。</p></div><CalendarDays size={28}/></div><div className="plan-controls"><label>开始日期<input type="date" value={s.settings.start} disabled={!ready} onChange={e=>setS(p=>({...p,settings:{...p.settings,start:e.target.value}}))}/></label><label>目标完成日期<input type="date" value={s.settings.end} disabled={!ready} onChange={e=>setS(p=>({...p,settings:{...p.settings,end:e.target.value}}))}/></label><label>每天可用时间（分钟）<input type="number" min="10" max="480" value={s.settings.minutes} disabled={!ready} onChange={e=>setS(p=>({...p,settings:{...p.settings,minutes:Number(e.target.value)}}))}/></label><button className="primary" disabled={!ready} onClick={makePlan}>生成学习计划</button></div>{notice&&<p role="status" className="notice">{notice}</p>}<div className="section-title"><h3>我的学习安排</h3><button disabled={!ready} onClick={()=>setS(p=>({...p,plan:[...p.plan,{date:p.settings.start||today(),text:'复习与实践',minutes:30,done:false}]}))}>＋ 添加安排</button></div>{!s.plan.length?<div className="empty">选择日期和每日时间，生成你的第一份计划。<br/><small>这里的日期与你参加培训的日期无关。</small></div>:s.plan.map((row,i)=><div className="plan-row" key={i}><Checkbox aria-label={`完成安排 ${i+1}`} checked={row.done} onCheckedChange={v=>setS(p=>({...p,plan:p.plan.map((r,j)=>j===i?{...r,done:!!v}:r)}))}/><input aria-label={`安排 ${i+1} 日期`} type="date" value={row.date} onChange={e=>setS(p=>({...p,plan:p.plan.map((r,j)=>j===i?{...r,date:e.target.value}:r)}))}/><input aria-label={`安排 ${i+1} 内容`} maxLength={150} value={row.text} onChange={e=>setS(p=>({...p,plan:p.plan.map((r,j)=>j===i?{...r,text:e.target.value}:r)}))}/><label><input aria-label={`安排 ${i+1} 分钟`} type="number" min="1" max="480" value={row.minutes} onChange={e=>setS(p=>({...p,plan:p.plan.map((r,j)=>j===i?{...r,minutes:Math.max(1,Math.min(480,Number(e.target.value)))}:r)}))}/> 分钟</label><button aria-label={`删除安排 ${i+1}`} onClick={()=>setS(p=>({...p,plan:p.plan.filter((_,j)=>j!==i)}))}>删除</button></div>)}<p className="muted">计划勾选只表示完成当天安排；请在课程模块中确认整体学习完成。修改后的日期与时长由你自行安排。</p></section></TabsContent>
 <TabsContent value="quiz"><section className="panel"><div className="section-title"><div><h2>用问题检查理解</h2><p>补充自测题，不是原课程试题。选择后显示解释，答案自动保存。</p></div><b>{quiz.filter((q,i)=>s.answers[i]===q.answer).length} / {quiz.length} 答对</b></div><div className="quiz-tools"><button className={reviewOnly?'primary':''} onClick={()=>setReviewOnly(!reviewOnly)}>{reviewOnly?'显示全部题目':'只看错题'}</button><button disabled={!ready} onClick={()=>{if(window.confirm('清除本次自测答案并重新开始？'))setS(p=>({...p,answers:Array(quiz.length).fill(null)}));}}><RotateCcw size={15}/>重新自测</button></div>{reviewOnly&&!quiz.some((q,i)=>s.answers[i]!=null&&s.answers[i]!==q.answer)&&<div className="empty">目前没有错题。完成自测后再来检查。</div>}{quiz.map((q,i)=>{if(reviewOnly&&(s.answers[i]==null||s.answers[i]===q.answer))return null;return <div className="question" key={i}><h3><span>{String(i+1).padStart(2,'0')}</span>{q.q}</h3><div className="options">{q.options.map((x,j)=><button key={j} disabled={!ready} aria-pressed={s.answers[i]===j} className={s.answers[i]===j?'chosen':''} onClick={()=>setS(p=>({...p,answers:p.answers.map((a,k)=>k===i?j:a)}))}><span>{'ABC'[j]}</span>{x}</button>)}</div>{s.answers[i]!=null&&<div className={'answer '+(s.answers[i]===q.answer?'correct':'incorrect')}><b>{s.answers[i]===q.answer?'回答正确':'再想一想'} · 正确答案 {'ABC'[q.answer]}</b><p>{q.why}</p><button onClick={()=>{setActive(q.module);setView('learn');}}>回看模块 {q.module+1} 与官方资料 →</button></div>}</div>;})}</section></TabsContent>
 <TabsContent value="practice"><div className="practice-grid"><section className="panel"><div className="section-title"><h2>实践验收清单</h2><span>建议任务</span></div><p>完成真实操作并留下证据后再勾选。本网页不执行 Ascend C 代码。</p>{tasks.map((x,i)=><label className="task" key={i}><Checkbox checked={s.tasks.includes(i)} disabled={!ready} onCheckedChange={()=>toggle('tasks',i)}/><span><b>{x}</b><small>{['产出：架构图与各层职责','产出：环境版本、命令、运行日志','产出：三阶段数据流与队列生命周期','产出：切分参数、覆盖范围、尾块策略','产出：源码、参考输出、误差与边界测试'][i]}</small></span></label>)}<div className="exercise"><b>没有昇腾运行环境？</b><p>先完成概念梳理、代码阅读与纸面 Tiling 设计。运行和输出验收留到真实环境完成，不把阅读进度当作运行成功。</p></div></section><section className="panel"><h2>复习工作台</h2><p>先尝试回忆，再打开笔记。错题可回到对应模块重学。</p><button className="primary" onClick={()=>{setReviewOnly(true);setView('quiz');}}>复习错题 <ArrowRight size={16}/></button><div className="section-title notes-heading"><h3>模块笔记</h3><button onClick={exportNotes}>导出笔记</button></div>{modules.map((x,i)=><details key={i}><summary>{String(i+1).padStart(2,'0')} · {x.title}<small>{s.notes[i]?'有笔记':'待记录'}</small></summary><p className="note-preview">{s.notes[i]||'暂未记录笔记。试着回答：这节课最关键的概念是什么？'}</p><button onClick={()=>{setActive(i);setView('learn');}}>回到模块编辑 →</button></details>)}</section></div></TabsContent>
 <TabsContent value="schedule"><div className="practice-grid"><section className="panel"><h2>原培训课表</h2><p>Ascend C 算子开发入门（Kernel 直调）</p><div className="schedule-list">{timetable.map(([time,title,duration])=><div key={time} className={title.includes('休息')||title.includes('无课程')?'break':''}><time>{time}</time><b>{title}</b><span>{duration}</span></div>)}</div><p className="notice">授课合计 5 小时 30 分钟 · 课间休息 45 分钟<br/>11:30—13:45 原课表无课程，不计入上述课间休息。</p><h3>原课表能力目标</h3><ol className="goals">{['理解 AI 发展历程、定义和应用','掌握昇腾基础软硬件平台架构、Atlas 产品和 CANN 的作用','理解算子定义、名称、类型、张量及其在模型中的作用','理解 NPU 内部架构及 AI Core 并行计算原理','掌握 Ascend C 核心特性与算子开发方法','编写符合规范的核函数，理解结构和语法','主机侧调用核函数以及数据和资源管理','理解矢量编程范式和 TPipe、TQue、TBuf','使用数据搬运、矢量计算和内存管理 API','构建并验证完整自定义算子'].map(x=><li key={x}>{x}</li>)}</ol></section><div><section className="panel"><h2>官方参考资料</h2><p>已按具体版本链接。培训未提供 CANN 版本；以下版本不代表课程指定或最新版本。实际开发请统一到所装 Toolkit、芯片和样例分支。</p>{sources.map(x=><a className="reference" key={x.url} href={x.url} target="_blank" rel="noreferrer"><span><b>{x.title}</b><small>{x.version}</small></span><ArrowUpRight size={18}/></a>)}<small>核对日期：2026-09-26。导读、练习和自测均为补充整理，不能代替完整官方文档。</small></section><section className="panel notification"><h2>原通知备忘</h2><span className="warning">用户提供的信息 · 未核验最新公告</span><p>面向华东师范大学全体学生。培训为 2026 年 9 月 28 日或 29 日 9:00—17:30，任选一天，或 28 日上午 + 29 日下午。地点：普陀校区，教室待通知。自带笔记本和备用电源。</p><p><b>培训报名截止：9 月 25 日 16:00。</b>截至 2026 年 9 月 26 日已过，补报请联系组织方。</p><p>原比赛安排：9 月 5 日发布初赛赛题；10 月 16 日 23:59 比赛报名截止；10 月 17 日提交作品；11 月 7 日区域决赛。报名选择上合赛区。以上时间均按原通知记录，以组织方确认信息为准。</p></section></div></div></TabsContent>
 </Tabs><footer><span>ASCEND C · 学习工坊</span><p>无需登录，学习记录保存在当前浏览器。更换设备或清除浏览器数据前，请使用“导出笔记”保存重要内容。</p><span>循序渐进，学以致用。</span></footer></main></div>;
}

